### ISSUE TITLE
Error minos-1.6.2 minos configure

### ISSUE THREAD

**Issue by swarbred** [EI-CoreBioinformatics/minos#34]
@gemygk 

Running minos.1.6.2 minos configure i'm getting an error (see attached file), running 1.6.1 completes ok

[std.err.txt](https://github.com/EI-CoreBioinformatics/minos/files/5497301/std.err.txt)

Looking in the logs directory the minos_run.mikado_configure.log file indicates an issue with scikit-learn (copied below)

I'm running this from /ei/projects/b/b3107fcd-8887-43d5-b18b-8d3f4cce1d12/data/results/CB-GENANNO-480_Bombus_vestalis_annotation/Analysis/minos-1.6.2

see the attached for the run command

```
Traceback (most recent call last):
  File "/ei/software/cb/minos/1.6.2/x86_64/lib/python3.6/site-packages/sklearn/__check_build/__init__.py", line 44, in <module>
    from ._check_build import check_build  # noqa
ModuleNotFoundError: No module named 'sklearn.__check_build._check_build'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mikado", line 5, in <module>
    from Mikado import main
  File "/ei/software/cb/minos/1.6.2/x86_64/lib/python3.6/site-packages/Mikado/__init__.py", line 26, in <module>
    from . import configuration
  File "/ei/software/cb/minos/1.6.2/x86_64/lib/python3.6/site-packages/Mikado/configuration/__init__.py", line 7, in <module>
    from . import configurator
  File "/ei/software/cb/minos/1.6.2/x86_64/lib/python3.6/site-packages/Mikado/configuration/configurator.py", line 21, in <module>
    from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
  File "/ei/software/cb/minos/1.6.2/x86_64/lib/python3.6/site-packages/sklearn/__init__.py", line 79, in <module>
    from . import __check_build  # noqa: F401
  File "/ei/software/cb/minos/1.6.2/x86_64/lib/python3.6/site-packages/sklearn/__check_build/__init__.py", line 46, in <module>
    raise_build_error(e)
  File "/ei/software/cb/minos/1.6.2/x86_64/lib/python3.6/site-packages/sklearn/__check_build/__init__.py", line 41, in raise_build_error
    %s""" % (e, local_dir, ''.join(dir_content).strip(), msg))
ImportError: No module named 'sklearn.__check_build._check_build'
___________________________________________________________________________
Contents of /ei/software/cb/minos/1.6.2/x86_64/lib/python3.6/site-packages/sklearn/__check_build:
__pycache__               __init__.py               _check_build.cpython-36m-x86_64-linux-gnu.so
setup.py
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.
```

**Comment by gemygk** [comment]
@swarbred I am looking into it now.

**Comment by gemygk** [comment]
@swarbred 

@cschu  and I had a chat and the v1.6.2 was not supposed to be sourceable from HPC as it is still under travis testing and that's why we get issues as above. The current production version is v1.6.1, which is what we are using now.

We can close this issue for now and create a new one if we have an issue then with the new `v1.6.2`. I will remove the wrapper for v1.6.2 from the cluster so that we do not use source it accidentally.

**Comment by gemygk** [comment]
wrapper removed `rm /ei/software/cb/bin/minos-1.6.2`
