### ISSUE TITLE
snakemake: copy is reserved for internal use

### ISSUE THREAD

**Issue by gemygk** [EI-CoreBioinformatics/minos#43]
Error when testing minos 1.7.0

Error log file:
```
/ei/.project-scratch/1/1c932027-ee3c-4575-953d-2876fa6fd8fe/CB-GENANNO-477_Minos_Arabidopsis/Analysis/minos/run1_170/MINOS_RUN.minos_output.err.log
```

Error
```Starting MINOS V 1.7.0

Runmode is run
Using run configuration file: /ei/.project-scratch/1/1c932027-ee3c-4575-953d-2876fa6fd8fe/CB-GENANNO-477_Minos_Arabidopsis/Analysis/minos/run1_170/minos_output/minos_run.run_config.yaml
[kaithakg@EI-HPC run1_170]$ cat MINOS_RUN.minos_output.err.log
Full Traceback (most recent call last):
  File "/ei/software/cb/python_miniconda/4.9.2_py3.8_minos/x86_64/lib/python3.8/site-packages/snakemake/__init__.py", line 591, in snakemake
    workflow.include(
  File "/ei/software/cb/python_miniconda/4.9.2_py3.8_minos/x86_64/lib/python3.8/site-packages/snakemake/workflow.py", line 1103, in include
    exec(compile(code, snakefile, "exec"), self.globals)
  File "/hpc-home/kaithakg/git_installations/minos/1.7.1/x86_64/lib/python3.8/site-packages/minos/zzz/minos_run.smk", line 1648, in <module>
  File "/ei/software/cb/python_miniconda/4.9.2_py3.8_minos/x86_64/lib/python3.8/site-packages/snakemake/workflow.py", line 1231, in decorate
    rule.set_params(*ruleinfo.params[0], **ruleinfo.params[1])
  File "/ei/software/cb/python_miniconda/4.9.2_py3.8_minos/x86_64/lib/python3.8/site-packages/snakemake/rules.py", line 602, in set_params
    self._set_params_item(item, name=name)
  File "/ei/software/cb/python_miniconda/4.9.2_py3.8_minos/x86_64/lib/python3.8/site-packages/snakemake/rules.py", line 607, in _set_params_item
    self.params._add_name(name)
  File "/ei/software/cb/python_miniconda/4.9.2_py3.8_minos/x86_64/lib/python3.8/site-packages/snakemake/io.py", line 1427, in _add_name
    self._set_name(name, len(self) - 1)
  File "/ei/software/cb/python_miniconda/4.9.2_py3.8_minos/x86_64/lib/python3.8/site-packages/snakemake/io.py", line 1438, in _set_name
    raise AttributeError(
AttributeError: invalid name for input, output, wildcard, params or log: copy is reserved for internal use

AttributeError in line 957 of /hpc-home/kaithakg/git_installations/minos/1.7.1/x86_64/lib/python3.8/site-packages/minos/zzz/minos_run.smk:
invalid name for input, output, wildcard, params or log: copy is reserved for internal use
  File "/hpc-home/kaithakg/git_installations/minos/1.7.1/x86_64/lib/python3.8/site-packages/minos/zzz/minos_run.smk", line 957, in <module>
```

**Comment by lucventurini** [comment]
OK, I will have a look immediately

**Comment by gemygk** [comment]
@lucventurini  I have done the fix and tested it
