### ISSUE TITLE
NameError: name 'BUSCO_TABLE' is not defined

### ISSUE THREAD

**Issue by gemygk** [EI-CoreBioinformatics/minos#48]
Reported by @swarbred 

We get the error below when providing `--busco-level none`

CMD:
```
source minos-1.7.1 && minos configure --mikado-container /ei/software/cb/mikado/2.0.1/x86_64/mikado-2.0.1.simg --busco-level none -o minos_output_noBusco_run3 --external-metrics external_metrics.txt --external external.yaml --use-tpm-for-picking --use-diamond --genus-identifier GESPE12345 --annotation-version EIv1.0 list.txt scoring_template.yaml sample_data/genome/scaffold_6.fa && minos run --mikado-container /ei/software/cb/mikado/2.0.1/x86_64/mikado-2.0.1.simg -o minos_output_noBusco_run3 --hpc_config hpc_config.json
```
Error log:
```
File:
/ei/.project-scratch/1/1c932027-ee3c-4575-953d-2876fa6fd8fe/CB-GENANNO-477_Minos_Arabidopsis/Analysis/minos/run1_171/out_minos_output_noBusco_run3.t128n32.34495250.log

...
...
Full Traceback (most recent call last):
  File "/ei/software/cb/python_miniconda/4.9.2_py3.8_minos/x86_64/lib/python3.8/site-packages/snakemake/__init__.py", line 591, in snakemake
    workflow.include(
  File "/ei/software/cb/python_miniconda/4.9.2_py3.8_minos/x86_64/lib/python3.8/site-packages/snakemake/workflow.py", line 1103, in include
    exec(compile(code, snakefile, "exec"), self.globals)
  File "/ei/software/cb/minos/1.7.1/x86_64/lib/python3.8/site-packages/minos/zzz/minos_run.smk", line 198, in <module>
NameError: name 'BUSCO_TABLE' is not defined

NameError in line 196 of /ei/software/cb/minos/1.7.1/x86_64/lib/python3.8/site-packages/minos/zzz/minos_run.smk:
name 'BUSCO_TABLE' is not defined
  File "/ei/software/cb/minos/1.7.1/x86_64/lib/python3.8/site-packages/minos/zzz/minos_run.smk", line 196, in <module>
Starting MINOS V 1.7.1
```

**Comment by gemygk** [comment]
Fixed issue with PR #49. Made release v1.7.2
